service-spanish:
  build: .
  image: shaunpersad/hello-service-spanish
  command: nodemon index.js
  environment:
    NODE_ENV: development
  links:
    - rabbitmq
  restart: always
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

